name: "Run CPU Tests"

on: "push"

jobs:
  run-tests-python3_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -e .[dev]

      - name: Run CPU Tests
        run: pytest -m cpu

  run-tests-python3_10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -e .[dev]

      - name: Run CPU Tests
        run: pytest -m cpu
