name: "Run CPU Tests"

on: "push"

jobs:
  run-tests:
    strategy:
      matrix:
        python-versions: [ "3.10", "3.11" ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -e .[dev]

      - name: Type Checking
        uses: jakebailey/pyright-action@v1

      - name: Run normal tests, excluding GPU tests
        run: pytest -m "not gpu"
